- name: list all the modules
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command:
      dnf module disable nodejs -y
  - name: enable default nodejs
    ansible.builtin.command:
      dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest
  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create a directory
    ansible.builtin.file:   
      path: /app
      state: directory
  - name: Download code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip # by default checks in ansible server
      dest: /app
      remote_src: yes
  - name: install npm dependancies
    ansible.builtin.command:
      npm install
      args:         #paina command run chese mundhi ee directory ki change avvu ani ansible ki chepthunam manam. And pakage.json ekada untado akade npm install run aytadi
        chdir: /app
  