- name: list all the modules
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command:
      dnf module disable nodejs -y
  - name: enable default nodejs
    ansible.builtin.command:
      dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest
  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create a directory
    ansible.builtin.file:   
      path: /app
      state: directory
  # - name: Download the application code to created app directory.
  #   ansible.builtin.command:   
  #     curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
  #     cd /app
  #     unzip /tmp/backend.zip
  #     cd /app
  #     npm install

  